---
Name: silverstripe-text
---
SiteConfig:
  extensions:
    - Font_SiteConfigExtension
    - FontSize_SiteConfigExtension

LeftAndMain:
  extra_requirements_css:
    - silverstripe-text/css/cms/min.css